spring:
  application:
    name: api

  # LOCALE ------------
  web:
    locale.resolver: fixed
    locale: pt_BR

  #DATABASE
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: db_user
    password: db_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect